name: Publish release artifacts to Maven

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: "Publish release artifacts to Maven"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: set up JDK 11
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Publish artifact
        env:
          UB_ARTIFACTORY_URL_ANDROID: ${{ secrets.UB_ARTIFACTORY_URL_ANDROID }}
          UB_ARTIFACTORY_USER: ${{ secrets.UB_ARTIFACTORY_USER }}
          UB_ARTIFACTORY_PASSWORD: ${{ secrets.UB_ARTIFACTORY_PASSWORD }}
          ARTIFACT_VERSION_NAME: ${{ github.ref_name }}
        run: ./gradlew :library:assembleRelease :library:publishAllPublicationsToUbiqueRepository
